# Generated by Django 3.1 on 2020-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0002_auto_20200810_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreentry',
            name='id',
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='UUID',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='conclusionTime',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='ghostInfo',
            field=models.CharField(max_length=1023),
        ),
    ]
