# Generated by Django 3.1 on 2020-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0005_auto_20200810_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
