# Generated by Django 3.1 on 2020-08-10 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0006_auto_20200810_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreentry',
            name='id',
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='userid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
