# Generated by Django 3.1 on 2020-08-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogo', '0007_auto_20200810_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreentry',
            name='ghostInfo',
            field=models.TextField(max_length=1000000),
        ),
    ]
